#!/usr/bin/env bash
# Install the web server 'nginx' on the server
sudo apt update -y

sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee  /var/www/html/index.html
sudo service nginx start