#!/usr/bin/env bash

# Install NGINX server
apt-get -y update
apt-get -y install nginx

# Set a custom 404 error page
sudo mkdir -p /var/www/error
echo "<html>
<head>
<title>404 Not Found</title>
</head>
<body>
<h1>404 Not Found</h1>
<p>Ceci n'est pas une page</p>
</body>
</html>" > /var/www/error/404.html

# Configure NGINX server to use the custom 404 error page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 http://fusedtc.tech/;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default

# Restart NGINX server to apply changes
systemctl restart nginx

