#!/usr/bin/env bash
# update and install nginx

# Update the package index and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Set up custom 404 page with the required string
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '/listen 80 default_server;/a \\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\tinternal;\n\t\troot \/var\/www\/html;\n\t}' /etc/nginx/sites-available/default


# Restart Nginx service to apply changes
sudo service nginx restart

