#!/usr/bin/env bash
# update and install nginx

sudo apt-get update
sudo apt-get install -y nginx

# create index and 404 pages
sudo tee /var/www/html/index.html > /dev/null <<EOF
Hello World!
EOF

sudo tee /var/www/html/404.html > /dev/null <<EOF
Ceci n'est pas une page
EOF

# configure nginx
sudo tee /etc/nginx/sites-available/custom404 > /dev/null <<EOF
server {
    listen 80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location = /404.html {
        internal;
    }

    error_page 404 /404.html;

    location = /redirect_me {
        rewrite ^ https://fusedtc.tech permanent;
    }
}
EOF

# remove the default config file and enable the custom one
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/custom404 /etc/nginx/sites-enabled/

# restart nginx
sudo systemctl restart nginx
