#!/usr/bin/env bash
# This will script install and configures HAProxy as a load balancer for two web servers.

# install HAproxy
sudo apt-get update
sudo apt-get -y install haproxy

# Open the HAproxy configuration file for editing
sudo vim /etc/haproxy/haproxy.cfg

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 60352-web-01 34.227.93.91:80 check\n\tserver 60352-web-02 100.25.0.41:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
