#!/usr/bin/env bash
# This script configures NginX to listen to :80
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx start 2>/dev/null
echo "" | sudo dd status=none of=/run/nginx.pid
