#!/usr/bin/env bash
# displays the content of the file /etc/passwd
# with only username, user id, and home dir path

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
