#!/usr/bin/env bash
# loop with condition if, elif and else
# on the 4th, 8th and Best School for all iteration

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done