#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20
# and for iteration:
#	displays 4 and then bad luck from China line 4
#	displays 9 and then bad luck from Japan line 9
#	displays 17 and then bad luck from Italy lin 17

num=1

while [ $num -le 20 ]
do
	echo "$num"
	case $num in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( num++ ))
done