#!/usr/bin/env bash
# This script configures a ufw firewall to block all incoming traffic
# Excepts for TCP ports 22, 443 and 80.

apt-get install ufw
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
