#!/usr/bin/env bash
# This script changes your home IP

cp /etc/hosts ~/hosts.new
sed -i 's/^127\.0\.0\.1\(.*\)localhost$/002\1localhost/' ~/hosts.new
sed -i "\$a8.8.8.8 facebook.com" ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
