#!/usr/bin/env bash

# This script configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8
# Since docker is used as the containment, these are the steps to follow

# Copy the contents of /etc/hosts to a new file in the user's home directory
sudo cp /etc/hosts ~/hosts.new

# Replace the line that maps localhost to 127.0.0.1 with a new line that maps it to 127.0.0.2, and maps facebook.com to 8.8.8.8
sudo sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new

# Overwrite the original /etc/hosts file with the modified hosts.new file
sudo cp -f ~/hosts.new /etc/hosts

echo "Done! Localhost now resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8."

# IMPORTANT: Be sure to revert the changes made to /etc/hosts after you're done testing!
# Run this command to revert the changes:
# sudo sed -i 's/127.*$/127.0.0.1 localhost/' /etc/hosts