#!/usr/bin/env bash
# This script displays all active IPv4 addresses on the machine.

# Retrieve the active network interfaces with IPv4 addresses
active_interfaces=$(ip -4 addr show | grep "inet " | awk '{print $NF}')

# Loop through each active interface and extract its IPv4 address
for interface in $active_interfaces; do
  ipv4_address=$(ip -4 addr show $interface | grep "inet " | awk '{print $2}' | cut -d "/" -f 1)
  echo $ipv4_address
done


